# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('thumb', models.ImageField(blank=True, null=True, upload_to='articles', verbose_name='Эскиз')),
                ('body', models.TextField(verbose_name='Содержимое')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='Ник')),
                ('firstname', models.CharField(blank=True, max_length=30, verbose_name='Имя')),
                ('lastname', models.CharField(blank=True, max_length=30, verbose_name='Фамилия')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Author'),
        ),
    ]
